### ISSUE TITLE
Error in api.request

### ISSUE THREAD

**Issue by heck1** [WillemPaling/RDoubleClick#1]
Hi,

been working with this package for a while now, using it to create an automated reporting for my firm's DCM-accounts. When I tried to login just now, I was able to login, but when I tried to run 

`files <- files.list(profileId,results=100)`
I got:
`Error in api.request(req.url, querystring = req.q.string) : 
  Forbidden (HTTP 403).`

I double checked and the login I am using works and has sufficient permissions for access (or at least used to have then?). 
Did something change I am unaware of?

Thanks in advance

**Comment by heck1** [comment]
okay, found the issue: in `files.list` ,you call 

`req.url <- paste0("https://www.googleapis.com/dfareporting/v2.2/userprofiles/",profileId,"/files")` , which is deprecated, just need to change it to "v2.3" and it works!

**Comment by WillemPaling** [comment]
Thanks. Are you able to submit a pull request with that change?

**Comment by kairos35** [comment]
Hi,  get the same error message, although authentification is successful
  
Error in api.request(req.url, querystring = req.q.string) : 
  Forbidden (HTTP 401).

Since I just downloaded the package it is already on
req.url <- paste0("https://www.googleapis.com/dfareporting/v2.5/userprofiles/",profileId,"/files")

Which other reasons might be possible? Thanks for any thoughts!

**Comment by PriyankaAvhad** [comment]
Hi, I get the same error too. Have changed v2.7 to v2.8 by using command:

body(files.list)[[12]][[3]][[3]] <- substitute(req.url <-
paste0("https://www.googleapis.com/dfareporting/v2.8/userprofiles/", profileId, "/files"))

I get the error: 
Error in api.request(req.url, querystring = req.q.string) : 
Internal Server Error (HTTP 500).

Any idea how to resolve this?

**Comment by WillemPaling** [comment]
Have you been through these steps:

After you create the client id and secret in the google APIs console, you also have to go in and enable the DCM Reporting API.

GO here: https://console.developers.google.com/apis/dashboard
Select your project.
Then click "enable API".
Then click on "DCM/DFA Reporting And Trafficking API"
Then click on "enable"

**Comment by kairos35** [comment]
HI,sorry for the short answer. Am currently in Afrika with not the best internet access ... please allow me to get back to you next week, when I am back in Europe.Thanks for your thoughts!Cheers, LucieOn 25 May 2017 at 11:34 Willem Paling <notifications@github.com> wrote:Have you been through these steps:After you create the client id and secret in the google APIs console, you also have to go in and enable the DCM Reporting API.GO here: https://console.developers.google.com/apis/dashboard Select your project. Then click "enable API". Then click on "DCM/DFA Reporting And Trafficking API" Then click on "enable"—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by PriyankaAvhad** [comment]
Thanks for the response. 
Yes, I have enabled the 'DCM/DFA Reporting And Trafficking API' for my project. I can see the API requests being made and number of errors thrown on the API manager dashboard.

**Comment by Th3Bust3r** [comment]
I had been successfully using this package to pull down files from DCM up until last week when I started getting this same error. Could this be related to a version change? Any help is appreciated!

**Comment by mdh1984** [comment]
@Th3Bust3r - I had the same issue. Looks like @kairos35 just needs to update to the 2.8 API. I fixed it in my code based on what @PriyankaAvhad had done above. Before you run the files.list() function, just add. 

body(files.list)[[12]][[3]][[3]] <- substitute(req.url <-
paste0("https://www.googleapis.com/dfareporting/v2.8/userprofiles/", profileId, "/files"))

Hope that works!

**Comment by Th3Bust3r** [comment]
Thanks @mdh1984 and @PriyankaAvhad that works perfectly!!

**Comment by WillemPaling** [comment]
This is an easy fix. Just a find/replace in the code. Feel free to submit a PR. Otherwise I'll try get it resolved in the next few weeks.
